######################################################## 
# Dockerfile for doci-db database container with MariaDB
######################################################## 
# Build from base image doci-base:latest adds package mariadb-server-10.1 (+250MB)
FROM doci-base:1.0.3 

# Author: Sean Peterson 
# Version: 0.0.8

MAINTAINER Sean Peterson <sean729@gmail.com> 

RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	echo mariadb-server-10.1 mysql-server/root_password password PASS | debconf-set-selections && \
	echo mariadb-server-10.1 mysql-server/root_password password PASS | debconf-set-selections

RUN \
	apt-get update && \
	apt-get install -y software-properties-common mariadb-server mariadb-client && \
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

