######################################################## 
# Dockerfile for doci-app 
######################################################## 
# Build from base doci image adding Java 1.8, Spring Boot 
FROM doci-builder:latest 
# Author: Sean Peterson 
# Version: 0.0.1

MAINTAINER Sean Peterson <sean729@gmail.com> 

RUN \
	add-apt-repository -y ppa:webupd8team/java && \
	echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
	apt-get update && \
	apt-get install -y oracle-java8-installer maven oracle-java8-set-default

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

