######################################################## 
# Dockerfile for doci-lbal nginx
######################################################## 
# Build from base image doci-base:latest for load balancer using nginx (+22 MB)
FROM doci-base:latest 

# Author: Sean Peterson 
# Version: 0.0.5

MAINTAINER Sean Peterson <sean729@gmail.com> 

#RUN echo exit 0 > /usr/sbin/policy-rc.d && \
#	apt-get update && \
#	apt-get install -y nginx


COPY \
	default-nginx.conf /etc/nginx/sites-available/default
	
	
#RUN \
#	service nginx restart